
# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup


import os.path

readme = ''
here = os.path.abspath(os.path.dirname(__file__))
readme_path = os.path.join(here, 'README.rst')
if os.path.exists(readme_path):
    with open(readme_path, 'rb') as stream:
        readme = stream.read().decode('utf8')


setup(
    long_description=readme,
    name='xepmts',
    version='0.4.12',
    description='Python client for accessing the XENON experiment PMT data.',
    python_requires='>=3.7',
    project_urls={"documentation": "https://xepmts.readthedocs.io/", "homepage": "https://github.com/jmosbacher/xepmts"},
    author='Yossi Mosbacher',
    author_email='joe.mosbacher@gmail.com',
    license='MIT',
    classifiers=['Development Status :: 2 - Pre-Alpha', 'Intended Audience :: Developers', 'License :: OSI Approved :: MIT License', 'Natural Language :: English', 'Programming Language :: Python :: 3.6', 'Programming Language :: Python :: 3.7', 'Programming Language :: Python :: 3.8'],
    entry_points={"console_scripts": ["xepmts = xepmts.cli:main"]},
    packages=['xepmts', 'xepmts.api', 'xepmts.api.server', 'xepmts.api.server.v1', 'xepmts.api.server.v2', 'xepmts.web_client', 'xepmts.web_client.src', 'xepmts.web_client.src.apps', 'xepmts.web_client.src.apps.gains_viewer', 'xepmts.web_client.src.apps.home', 'xepmts.web_client.src.assets', 'xepmts.web_client.src.shared', 'xepmts.web_client.src.shared.modifications'],
    package_dir={"": "."},
    package_data={"xepmts.api": ["endpoints/*.yml"], "xepmts.web_client": ["*.cfg", "*.ini", "*.md", "*.toml", "*.txt", "requirements/*.txt"], "xepmts.web_client.src": ["config/*.toml"], "xepmts.web_client.src.apps": ["pandas_profiling/*.yaml"], "xepmts.web_client.src.apps.home": ["*.md"]},
    install_requires=['click', 'eve-panel==0.*,>=0.3.12', 'holoviews==1.*,>=1.14.2', 'toml==0.*,>=0.10.2', 'xeauth==0.*,>=0.1.2'],
    extras_require={"dask": ["dask[dataframe]==2021.*,>=2021.2.0"], "dev": ["bumpversion", "coverage", "flake8", "invoke", "isort", "nbsphinx", "numpydoc", "pylint", "pytest", "sphinx", "sphinx-material", "tox", "yapf"], "full": ["awesome-panel-extensions==20210124.*,>=20210124.1.0", "dask[dataframe]==2021.*,>=2021.2.0", "eve-jwt==0.*,>=0.1.9", "flask-swagger-ui==3.*,>=3.36.0", "hvplot==0.*,>=0.7.0", "prometheus-flask-exporter==0.*,>=0.18.1"], "plotting": ["hvplot==0.*,>=0.7.0"], "server": ["eve-jwt==0.*,>=0.1.9", "flask-swagger-ui==3.*,>=3.36.0", "prometheus-flask-exporter==0.*,>=0.18.1"], "webclient": ["awesome-panel-extensions==20210124.*,>=20210124.1.0"]},
)
