version: '3'

services:
  explorer:
    image: gcr.io/xenon-pmts/pmtdb_production_explorer:latest
    container_name: pmtdb_production_explorer
    expose:
      - "5006"
    networks:
      - web
    environment:
      - DOMAIN=${DOMAIN}
    env_file:
      - ./.env
    restart: always
    labels:
      traefik.enable: true
      traefik.docker.network: web
      traefik.http.routers.explorer.entrypoints: websecure
      traefik.http.routers.explorer.tls: true
      traefik.http.routers.explorer.tls.certresolver: myresolver
      traefik.http.routers.explorer.rule: Host(`explorer.${DOMAIN}`)
      traefik.http.services.explorer.loadbalancer.sticky.cookie: true
      

networks:
  web:
    external: true
